import '../styles/GlobalStyles.css'
import {Toaster} from 'react-hot-toast';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<>
    <html lang="en">
      <body>
        <Toaster/>
        {children}
        <Toaster position="bottom-center" toastOptions={{duration: 3000}
      }/>
        </body>
    </html></>
  )
}
